### ISSUE TITLE
This is AWESOME, but hard to find

### ISSUE THREAD

**Issue by rtlong** [hotwatermorning/auto-git-diff#6]
I found this while looking for anything to help with a large interactive rebase where I wanted to squash many commits together but had no idea what they contained. It's totally awesome, because I happen to use vim. I notice, though, that nowhere in the repo description or README do you mention that auto-git-diff is a vim plugin! Might be helpful to others to help find this great tool.

**Comment by hotwatermorning** [comment]
Thank you for your comment and I'm very glad to hear that you said "this great tool".
I'll mention about vim plugin in REAME.md following your advice.
